# Project Euler
# Problem 2: Even Fibonacci Numbers
# Problem Details:
#     Each new term in the Fibonacci sequence is generated by
#     adding the previous two terms.  By starting with 1 and 2, the first 10 terms will be:
#     1, 2, 3, 5, 8 , 13, 21, 34, 55, 89
#     By considering the terms in the Fibonacci sequence whose values do not exceed four
#     million, find the sum of the even- valued terms.


# Jeffrey Spahn
# created for Python 3.x

sum = 2
a1 = 1
a2 = 2
a3 = a1 + a2

while a3 < 4000000:
    a1 = a2
    a2 = a3
    a3 = a1+a2

    if a3 % 2 == 0:
        sum += a3

print("The sum of all even Fibonacci numbers below 4,000,000 is: " + str(sum))

# Output: The sum of all even Fibonacci numbers below 4,000,000 is: 4613732

